export const dbRes = {
    txList:{
        record_id:1,
        base_denom:1,
        dc_addr:1,
        'dc_tx_info.hash':1,
        dc_chain_id:1,
        sc_chain_id:1,
        sc_channel:1,
        dc_channel:1,
        sequence:1,
        denoms:1,
        sc_addr:1,
        'sc_tx_info.hash':1,
        tx_time:1,
        status:1,
        'sc_tx_info.msg_amount':1,
        'sc_tx_info.time':1,
        'sc_tx_info.status':1,
        'dc_tx_info.time':1,
        'refunded_tx_info.time':1,
    }
}